public class Problem2 {
public static void main(String[] args) {
    //  Each new term in the Fibonacci sequence is generated by adding the previous 
    //  two terms. By starting with 1 and 2, the first 10 terms will be:
    //  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    // 
    //  By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
    //  find the sum of the even-valued terms.
    int max = 4000000;
    int count = 0;
    long sum = 0;
    int n1 = 0;
    int n2 = 1;
    int n3 = n1 + n2;
    while ( n3 <= max ) {
        if ( n3 % 2 == 0 )
            sum += n3;
        n1 = n2;
        n2 = n3;
        n3 = n1 + n2;
    }
    System.out.println("Sum of even fibonacci numbers under 4 million: " + sum);
}
}
